In [103]:
import random
import re

import numpy as np
import pandas as pd
from scipy.special import binom

In [42]:
df=pd.read_csv("3.csv", dtype=str)
df.iloc[1]

In [45]:
colnames = [f"Castle {x}" for x in range(1,11)]
patt = re.compile('\d+')
def valid_row(row):
    out = []
    for colname in colnames:
        e = row[colname]
        if patt.fullmatch(e):
            out.append(int(e))
        else:
            return None
    if sum(out) == 100:
        return out
    else:
        return None

def build_matrix(df):
    outfull = []
    for r in df.iterrows():
        out = valid_row(r[1])
        if out is not None:
            outfull.append(out)        
    return np.array(outfull)
    
m = build_matrix(df)
m

In [51]:
m.shape

In [52]:
m.dtype

In [79]:
s = np.array([range(1,11)])
def score2(r1, r2):
    s_gt = np.greater(r1, r2).astype(int) * s
    s_lt = np.less(r1, r2).astype(int) * s
    #print(s_gt)
    #print(s_lt)
    return np.sum(s_gt) - np.sum(s_lt)

score2(m[0], m[1])

11

In [82]:
out = []
l = m.shape[0]
for i in range(l):
    for j in range(i+1, l):
        out.append([i,j,score2(m[i], m[j])])
df = pd.DataFrame(out, columns=['i', 'j', 'score'])
df

i     j  score
0          0     1     11
1          0     2    -15
2          0     3     -1
3          0     4      2
4          0     5     -6
...      ...   ...    ...
871855  1317  1319    -16
871856  1317  1320     -2
871857  1318  1319    -14
871858  1318  1320      3
871859  1319  1320     -3

[871860 rows x 3 columns]

In [92]:
a = df[df.score > 0].groupby('i')['score'].count()
a

i
0       745
1       329
2       832
3       528
4       800
       ... 
1313      4
1314      3
1315      1
1317      1
1318      1
Name: score, Length: 1317, dtype: int64

In [93]:
b = df[df.score < 0].groupby('j')['score'].count()
b

In [100]:
df2 = pd.DataFrame(a.add(b, fill_value=0))
df2.sort_values('score', ascending=False)[:10]

score
926   967.0
679   963.0
472   951.0
854   937.0
995   934.0
1237  934.0
1168  927.0
232   921.0
145   920.0
1297  913.0

In [99]:
m[926]

array([ 0,  0, 12,  1,  1, 23,  3,  3, 33, 24])

In [66]:
def random_dist():
    d = np.zeros(shape=(10,))
    for i in range(100):
        d[random.randint(0, 9)] += 1
    return d

In [67]:
t1 = random_dist()
t2 = random_dist()

In [24]:
t1, t2

(array([13.,  9.,  9., 12., 14.,  8.,  5.,  6., 16.,  8.]),
 array([ 9.,  7., 14.,  9., 13., 12., 10., 10.,  8.,  8.]))

In [64]:
def score(d1, d2):
    s = 0
    for i, (c1, c2) in enumerate(zip(d1, d2), start=1):
        #print(i, c1, c2)
        if c1 > c2:
            s += i
        elif c1 < c2:
            s -= i
    return s
        
score(m[0], m[1])

11

In [104]:
binom(10,5)

252.0

In [105]:
binom(100,10)

17310309456440.0

In [107]:
n = 100
r = 10
binom(n+r-1,r-1)

4263421511270.9995